# Generated by Django 6.0.2 on 2026-03-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notification_user_id_notification_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='wallet_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
