# Generated by Django 6.0.2 on 2026-02-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(choices=[('FROZEN', 'Frozen'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('ACTIVE', 'Active'), ('CLOSED', 'closed')], default='ACTIVE', max_length=10),
        ),
    ]
